import base from '~/assets/base/glass.png';
import sprite2 from '~/assets/maps/cidade1/Outside_A2.png';
import sprite1 from '~/assets/maps/cidade1/sprite1.png';

export default {
  name: 'Cidade 1',
  base,
  sprites: [sprite1, sprite2],
  tiles: [
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 1, x: 3 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 5, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 5, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 5, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 5, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 5, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 5, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 5, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 1, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],

    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 4, x: 3 }, animate: true },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: true,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: true,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 4, x: 0 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 4, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 3 }, animate: true },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 0 }, animate: true },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 4, x: 3 }, animate: true },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 0, x: 0 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 2, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 2, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 0, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 3, x: 3 }, animate: true },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 0, x: 3 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 2, x: 2 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 0, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: { y: 1, x: 3 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 5, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'water',
        passing: 0,
        sprite: { id: 0, position: { y: 1, x: 1 }, animate: true },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'grass01',
        passing: 0,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
    [
      {
        tile: 'water',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
      {
        tile: 'rock',
        passing: 2,
        sprite: { id: 0, position: false },
        up: false,
      },
    ],
  ],
};
