export const mapa1 = [
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: true },
    { tile: 'grass01', passing: 0, up: true },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
    { tile: 'water', passing: 2, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
    { tile: 'grass01', passing: 0, up: false },
  ],
  [
    { tile: 'water', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
    { tile: 'rock', passing: 2, up: false },
  ],
];
